import type { Item } from "../../shared/models/models";

const uuid = () => crypto.randomUUID();

export const allItems: Item[] = [
  {
    inventoryId: uuid(),
    id: "dagger",
    name: "Dagger",
    description: "A small sharp blade",
    type: "weapon",
    stat: "attack",
    value: 1,
    coinCost: 50,
  },
  {
    inventoryId: uuid(),
    id: "sword",
    name: "Sword",
    description: "A basic sword",
    type: "weapon",
    stat: "attack",
    value: 2,
    coinCost: 100,
  },
  {
    inventoryId: uuid(),
    id: "broadsword",
    name: "BroadSword",
    description: "Heavy sword with high damage",
    type: "weapon",
    stat: "attack",
    value: 5,
    coinCost: 80,
  },
  {
    inventoryId: uuid(),
    id: "mace",
    name: "Mace",
    description: "Blunt weapon",
    type: "weapon",
    stat: "attack",
    value: 4,
    coinCost: 90,
  },
  {
    inventoryId: uuid(),
    id: "axe",
    name: "Axe",
    description: "Sharp axe",
    type: "weapon",
    stat: "attack",
    value: 6,
    coinCost: 120,
  },
  {
    inventoryId: uuid(),
    id: "double_axe",
    name: "Double Axe",
    description: "Two-headed axe",
    type: "weapon",
    stat: "attack",
    value: 7,
    coinCost: 150,
  },
  {
    inventoryId: uuid(),
    id: "spear",
    name: "Spear",
    description: "Long ranged weapon",
    type: "weapon",
    stat: "attack",
    value: 5,
    coinCost: 110,
  },

  {
    inventoryId: uuid(),
    id: "wooden_shield",
    name: "Wooden Shield",
    description: "Basic protection",
    type: "shield",
    stat: "defense",
    value: 5,
    coinCost: 50,
  },
  {
    inventoryId: uuid(),
    id: "plate_shield",
    name: "Plate Shield",
    description: "Strong shield",
    type: "shield",
    stat: "defense",
    value: 10,
    coinCost: 100,
  },

 
  {
    inventoryId: uuid(),
    id: "plate_armor",
    name: "Plate Armor",
    description: "Heavy armor",
    type: "armor",
    stat: "defense",
    value: 5,
    coinCost: 100,
  },

  
  {
    inventoryId: uuid(),
    id: "iron_helmet",
    name: "Iron Helmet",
    description: "Sturdy helmet",
    type: "helmet",
    stat: "defense",
    value: 3,
    coinCost: 70,
  },
  {
    inventoryId: uuid(),
    id: "plate_helmet",
    name: "Plate Helmet",
    description: "Heavy helmet",
    type: "helmet",
    stat: "defense",
    value: 5,
    coinCost: 80,
  },

 
  {
    inventoryId: uuid(),
    id: "blue_potion",
    name: "Blue Potion",
    description: "Restores energy",
    type: "potion",
    stat: "defense",
    value: 20,
    coinCost: 30,
  },
];