import type { Item } from "../../../shared/models/item"

export const items: Item[] = [
  {
    id: 1,
    name: "Sword",
    description: "Basic sword",
    type: "weapon",
    stat: "attack",
    value: 100,
  },
  {
    id: 2,
    name: "BroadSword",
    description: "Heavy sword",
    type: "weapon",
    stat: "attack",
    value: 80,
  },
  {
    id: 3,
    name: "Dagger",
    description: "Fast weapon",
    type: "weapon",
    stat: "attack",
    value: 50,
  },
  {
    id: 4,
    name: "Axe",
    description: "Strong axe",
    type: "weapon",
    stat: "attack",
    value: 70,
  },
  {
    id: 5,
    name: "Double Axe",
    description: "Two-handed axe",
    type: "weapon",
    stat: "attack",
    value: 90,
  },
  {
    id: 6,
    name: "Spear",
    description: "Long reach weapon",
    type: "weapon",
    stat: "attack",
    value: 100,
  },
  {
    id: 7,
    name: "Wooden Shield",
    description: "Basic shield",
    type: "shield",
    stat: "defense",
    value: 50,
  },
  {
    id: 8,
    name: "Plate Shield",
    description: "Heavy shield",
    type: "shield",
    stat: "defense",
    value: 100,
  },
  {
    id: 9,
    name: "Plate Armor",
    description: "Heavy armor",
    type: "armor",
    stat: "defense",
    value: 100,
  },
  {
    id: 10,
    name: "Iron Helmet",
    description: "Iron protection",
    type: "helmet",
    stat: "defense",
    value: 100,
  },
  {
    id: 11,
    name: "Plate Helmet",
    description: "Strong helmet",
    type: "helmet",
    stat: "defense",
    value: 80,
  },
  {
    id: 12,
    name: "Blue Potion",
    description: "Restores defense temporarily",
    type: "potion",
    stat: "defense",
    value: 30,
  },
];